@echo off
echo Starting MarketLens Project...
echo Starting backend server...
start cmd /k "cd backend && npm run dev"
echo Starting frontend development server...
start cmd /k "cd frontend && npm run dev"
echo Both servers are starting in new windows.
